# 共通設定（どの環境でも使う項目）
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# 開発環境（MySQLを使用）
development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_47736_development

# テスト環境（MySQLを使用）
test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_47736_test
  prepared_statements: false

production:
  <<: *default
  adapter: mysql2
  database: furima_47736_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
